#!/usr/bin/env bash #this makes the script portable
# set -n 
# set -x
# set -e 

# Author: Doctype Human

# Date:24.03.21

# Purpose: Passing parameters to functions

# License: GNU GENERAL PUBLIC LICENSE. VERSION 3, 2007
pass_parameters()					# Create a function
{
	m=$1						# Use a variable where the value is $1 which is the first parameter that is passed to the function
	n=$2						# Use a variable where the value is $2 which is the second parameter that is passed to the function
	sum=$((m+n))					# Command that will be carried out on the variables. 
	echo "If you add $m and $n you will get: $sum"	# Display result
}
a=1							# Random variable created which will be passed to the function as a parameter
b=2							# Random variable created which will be passed to the function as a parameter
pass_parameters $a $b					# Passed the variables with spaces between them to the function as parameters.
							# These are assigned $1 and $2 values in the function.

							
c=3
d=4
pass_parameters $c $d


pass_parameters 5 6					# When passing values to the function they need to be written alongside the function with a space in between them
exit

